#
# Copyright (C) 2019, Varphone Wong <varphone@qq.com>
#
# Copyright (C) 2019 NanJing No.55 Research Institue Technology Development Co.,LTD
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := jycz2.o
