#
# MYZR Technology Co.,Ltd
# http://www.myzr.com.cn
# Tang Bin <tangb@myzr.com.cn>
#

obj-$(CONFIG_TARGET_MYIMX6EK200)	:= myimx6a9.o
obj-$(CONFIG_TARGET_MYIMX6EK314)	:= myimx6a9.o
obj-$(CONFIG_TARGET_MYIMX6EK336)	:= myimx6a9.o
obj-$(CONFIG_TARGET_MYIMX6EK140)	:= myimx6a7.o
obj-$(CONFIG_TARGET_MYIMX6EK140P)	:= myimx6a7.o
